FROM nginx:1.25

# Remover configuração padrão do Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiar configuração personalizada
COPY nginx.conf /etc/nginx/conf.d/

# Expor porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]